POST http://10.1.0.5:5000/ordenesprovedorabiertas
Content-Type: application/json
Authorization:Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiTm9tYnJlRGVVc3Vhcm8iLCJpYXQiOjE2NzUxODQ5NDl9.5VSegYSNoFj4FeSJyvRc2ocHcJDK7JYgJ-TWMkV8ng8
    
    {
        "cuit":"30-71714701-0"
    }
