POST http://127.0.0.1:5000/ordenesprovedor
Content-Type: application/json
Authorization:Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiTm9tYnJlRGVVc3Vhcm8iLCJpYXQiOjE2NzQ3NzgxMzJ9.zMOe2yxfrDQ1WcnF-a1wow5WgYkPRZlhjZqFnk8JyiY
    
    {
    "cuit":"27-10613509-1"
    }
